// <auto-generated />
using System;
using InventoryList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryList.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260324175959_AddInventoryTemplates")]
    partial class AddInventoryTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("InventoryList.Models.InventoryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InventoryTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryTemplateId");

                    b.ToTable("InventoryGroups");
                });

            modelBuilder.Entity("InventoryList.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CUVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cores")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullVersion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KBVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPatchedOn")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OS")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Onboarded")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Product")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RAM")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryProcess")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryGroupId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("InventoryList.Models.InventoryTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryTemplates");
                });

            modelBuilder.Entity("InventoryList.Models.InventoryGroup", b =>
                {
                    b.HasOne("InventoryList.Models.InventoryTemplate", "InventoryTemplate")
                        .WithMany("Groups")
                        .HasForeignKey("InventoryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InventoryTemplate");
                });

            modelBuilder.Entity("InventoryList.Models.InventoryItem", b =>
                {
                    b.HasOne("InventoryList.Models.InventoryGroup", "InventoryGroup")
                        .WithMany("Items")
                        .HasForeignKey("InventoryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryGroup");
                });

            modelBuilder.Entity("InventoryList.Models.InventoryGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryList.Models.InventoryTemplate", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
